version: "3.6"
services:
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile 
    container_name: ${APP_NAME}_app
    restart: unless-stopped
    environment:
      - COMPOSER_VERSION=2.4.4
    volumes:
      - ./project:/var/www/html
    depends_on:
      - db
    ports:
    - "8003:8000"

# uncomment this lines if you want to use postgresql instead of mysql
  # db:
  #     image: postgres:14
  #     container_name: ${APP_NAME}_postgresql
  #     restart: unless-stopped
  #     environment:
  #       POSTGRES_DB: ${APP_NAME}
  #       POSTGRES_USER: root
  #       POSTGRES_PASSWORD: 123
  #     volumes:
  #       - ./postgresql:/var/lib/postgresql/data


  db:
    image: mysql:5.7
    restart: always
    hostname: db
    volumes:
      - ./mysql:/var/lib/mysql
    # uncomment this line if you are using mac os 
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: ${APP_NAME}

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_pma
    # uncomment this line if you are using mac os 
    platform: linux/x86_64
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8182:80
